listen_address = "127.0.0.1:45935"

# superseeded by systemd socket if available
unix_socket = "/run/led-matrix/led-matrix.sock"

max_queue_size = 100
num_http_workers = 4

[left_port]
path = "/dev/ttyACM1"
baud_rate = 115200
timeout = "2s"
keep_open = true

[right_port]
path = "/dev/ttyACM0"
baud_rate = 115200
timeout = "2s"
keep_open = true
